defaults:
#  - task: mnist_classification


  # - task@overriden_package_name: mnist_classss -> bu configi kopyalamış olduk 
#  - task@some_other_task: mnist_classification
#  - task@yet_another_task: mnist_classification


  # - /task/model/simple_model@overrinden_package_name -> tamamen aynı kopyayı burdada buldu
  - /task/model/simple_model@my_simple_model



